const productsArray = [
  {
    name: "Display Cabinet",
    image: "assets/img/vintage01.png",
    id: 01,
    price: 30.2,
    inStock: 10,
    numberOfUnits: 0,
  },
  {
    name: "Chest Of Drawers",
    image: "assets/img/vintage02.png",
    id: 02,
    price: 99.1,
    inStock: 10,
    numberOfUnits: 0,
  },
  {
    name: "Wooden Stool",
    image: "assets/img/vintage03.png",
    id: 03,
    price: 60.0,
    inStock: 10,
    numberOfUnits: 0,
  },
  {
    name: "Covered Desk",
    image: "assets/img/vintage04.png",
    id: 04,
    price: 20.0,
    inStock: 10,
    numberOfUnits: 0,
  },
  {
    name: "Side Cupboard",
    image: "assets/img/vintage05.png",
    id: 05,
    price: 80.0,
    inStock: 10,
    numberOfUnits: 0,
  },
  {
    name: "Antique Globe",
    image: "assets/img/vintage06.png",
    id: 06,
    price: 20.0,
    inStock: 10,
    numberOfUnits: 0,
  },
  {
    name: "Sideboard",
    image: "assets/img/vintage07.png",
    id: 07,
    price: 60.0,
    inStock: 10,
    numberOfUnits: 0,
  },
  {
    name: "Tall Cupboard",
    image: "assets/img/vintage08.png",
    id: 08,
    price: 40.0,
    inStock: 10,
    numberOfUnits: 0,
  },
];
